name: dart_cli_japanese_kanji_quiz
description: Japanese Kanji Quiz app using kanjiapi 
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '^3.5.0'

dependencies:
  http: 1.2.2
  retry: ^3.1.2
  dio: ^5.7.0

dev_dependencies:
  lint: ^2.0.0